export const skill = [
  { value: "Flutter", label: "Flutter" },
  { value: "Kotlin", label: "Kotlin" },
  { value: "Swift", label: "Swift" },
  { value: "AWS", label: "AWS" },
  { value: "C", label: "C" },
  { value: "C#", label: "C#" },
  { value: "C++", label: "C++" },
  { value: "Django", label: "Django" },
  { value: "Golang", label: "Golang" },
  { value: "Java", label: "Java" },
  { value: "MariaDB", label: "MariaDB" },
  { value: "MongoDB", label: "MongoDB" },
  { value: "MySQL", label: "MySQL" },
  { value: "Node.js", label: "Node.js" },
  { value: "PHP", label: "PHP" },
  { value: "Python", label: "Python" },
  { value: "Spring", label: "Spring" },
  { value: "Spring Boot", label: "Spring Boot" },
  { value: "Blockchain", label: "Blockchain" },
  { value: "Git", label: "Git" },
  { value: "Linux", label: "Linux" },
  { value: "PyTorch", label: "PyTorch" },
  { value: "Ruby on Rails", label: "Ruby on Rails" },
  { value: "Tensorflow", label: "Tensorflow" },
  { value: "Angular JS", label: "Angular JS" },
  { value: "CSS3", label: "CSS3" },
  { value: "Express.js", label: "Express.js" },
  { value: "Gatsby", label: "Gatsby" },
  { value: "HTML 5", label: "HTML 5" },
  { value: "Javascript", label: "Javascript" },
  { value: "jQuery", label: "jQuery" },
  { value: "Nuxt.js", label: "Nuxt.js" },
  { value: "React", label: "React" },
  { value: "React Native", label: "React Native" },
  { value: "Typescript", label: "Typescript" },
  { value: "Vue.js", label: "Vue.js" },
];
